### ISSUE TITLE
error on running from command line and dashboard

### ISSUE THREAD

**Issue by onstat** [inigoflores/lora-packet-forwarder-analyzer#1]
HI

thanks for the great tools.

Just thought Id check to see if you know what this error could be?

admin@Panther-X2:~/lora-packet-forwarder-analyzer$ ./processlogs.php

Using logs in /var/log/packet-forwarder/packet_forwarder.log

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 379909288 bytes) in /home/admin/lora-packet-forwarder-analyzer/processlogs.php on line 131

Thanks Stu

**Comment by inigoflores** [comment]
Hi

Sorry for the late reply. 

I can't reproduce the error, as the tool won't fail with my logs. Please upload your log files so I can run tests with them.

Thanks

**Comment by onstat** [comment]
Hi

Mine started working after the last Miner dashboard update but I have a further error now sorry.  Ive logged it on the panther dashboard but its this below


"Analysis log with LoRa Packet Forwarder Analyzer" stops working if the log size gets too big. Im my case its always less than 24 hours before it fills up as I have lots of non helium lora signals hitting my aerial.

The error I get on screen is below with nothing else showing

"Using logs in /var/log/packet-forwarder/packet_forwarder.log"

Clearing my log down to a smaller size fixes the issue and the analyser starts working with the following commands

sudo su
cd /var/log/packet-forwarder/
truncate -s 5k packet_forwarder.log

This only lasts for a day though and then it stops working. any chance of a fix in later versions please?

**Comment by inigoflores** [comment]
Hi

I run the tool without problems on the Panther X2 on files up to 10 Mb, which is the maximum size before log files rotate. Therefore, I believe the problem must be elsewhere. 

Make sure you are on the latest version by running `git pull`  in the `lora-packet-forwarder-analyzer` folder.

Is it possible for you to upload a log file that produces this error?

**Comment by onstat** [comment]
Thanks for the info.  Do you know where the log files rotate or is it on the same file in /var/log/packet-forwarder/?  Mine just keeps expanding so I wonder if the rotation isn't working for me?

Do you know where Id find a log file of the error?

thanks Stu

**Comment by onstat** [comment]
update. I just ran the command from the command line and after a short delay it runs fine!

I expect its some problem with panthers dashboard that is timing out and not returning the results after this small delay.

Ill report to panther

**Comment by inigoflores** [comment]
I've never run across this error in the command line. I most certainly has to do with the dashboard. Reporting this error to the devs at Panther is a good idea.
