### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by larrybml** [inigoflores/lora-packet-forwarder-analyzer#2]
I have three pisces p100 running your script, on 2 of them , witch are working ok, I get rx data and witness , but on one of them, witch is working bad, I get only witness . Do you know why I can't receive any rx data on it? Can it have a problem? 
Thank you in advance!

**Comment by inigoflores** [comment]
Hi

Sorry for the late reply.

This behaviour seems to indicate some bad element at the RF side. Witnesseses reach your hotspot at higher RSSI and using the more favorable SF12BW125 datarate, this is why they are more easily received.

Check the cables, in particular the SMA to N-Female pigtail inside the P100, which is usually overbent and sometimes damaged. I have found that most of the P100 have this issue, resulting in packet loss ranging from 5% to 50%. I sometimes replace it with the bluetooth cable (which is longer), but this will render your bluetooth unusable until you order another cable (the LoRa pigtail is too short).

I hope it helps.

Kind regards
